"""
Generate figures for CHW diabetes A1c manuscript.

Figure 1 (two-panel): treatment effect estimates + Q1 subgroup trajectories.
eFigure 1: propensity score distributions (generated by reanalysis.py).
eFigure 2: cost-effectiveness plane with Monte Carlo draws.
"""
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.linear_model import LogisticRegression

BASE = Path(__file__).resolve().parents[1]
FIG_DIR = BASE / "figures"
FIG_DIR.mkdir(exist_ok=True)

PARQUET = BASE / "data" / "analytic_cohort.parquet"
REANALYSIS = BASE / "output" / "reanalysis_results.json"
SENSITIVITY = BASE / "output" / "sensitivity_results.json"
MEAN_A1C = BASE / "output" / "mean_a1c_sensitivity_results.json"
CE_RESULTS = BASE / "output" / "cost_effectiveness_results.json"

cohort = pd.read_parquet(PARQUET)
with open(REANALYSIS) as f:
    res = json.load(f)
with open(SENSITIVITY) as f:
    sens = json.load(f)
with open(MEAN_A1C) as f:
    mean_a1c = json.load(f)
with open(CE_RESULTS) as f:
    ce = json.load(f)

# PS trimming (same as reanalysis)
COVARIATES = ["age", "baseline_a1c", "risk_percentile", "comorbidity_count",
              "pre_ed", "pre_ip", "pre_pcp", "has_bh", "has_htn",
              "has_chf", "has_pulm", "polypharmacy", "high_ed_ip"]
full = cohort.dropna(subset=COVARIATES + ["a1c_change"]).copy()
X_ps = full[COVARIATES].values.astype(float)
T_ps = full["treated"].values.astype(float)
ps = LogisticRegression(max_iter=1000).fit(X_ps, T_ps).predict_proba(X_ps)[:, 1]
trimmed = full[(ps >= 0.05) & (ps <= 0.95)].copy()

# ============================================================
# FIGURE 1: Two-panel (Panel A: estimate bars, Panel B: Q1 trajectories)
# ============================================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5), gridspec_kw={"width_ratios": [1.2, 1]})

# --- Panel A: Treatment effect estimates (primary + sensitivity) ---
estimates = [
    ("DML, mean HbA1c\n(primary, N={})".format(mean_a1c["mean_a1c_full_cohort"]["n"]),
     mean_a1c["mean_a1c_full_cohort"]["ate"],
     mean_a1c["mean_a1c_full_cohort"]["ci_lo"], mean_a1c["mean_a1c_full_cohort"]["ci_hi"]),
    ("DML, last HbA1c\n(sensitivity, N=369)",
     res["dml_full_cohort"]["ate"],
     res["dml_full_cohort"]["ci_lower"], res["dml_full_cohort"]["ci_upper"]),
]

labels = [e[0] for e in estimates]
ates = [e[1] for e in estimates]
ci_los = [e[2] for e in estimates]
ci_his = [e[3] for e in estimates]
errors_lo = [a - lo for a, lo in zip(ates, ci_los)]
errors_hi = [hi - a for a, hi in zip(ates, ci_his)]

y_pos = np.arange(len(labels))
colors = ["#2171b5", "#6baed6"]

ax1.barh(y_pos, ates, xerr=[errors_lo, errors_hi], height=0.5,
         color=colors, edgecolor="black", linewidth=0.5, capsize=4, error_kw={"linewidth": 1.2})
ax1.axvline(x=0, color="black", linewidth=0.8, linestyle="-")
ax1.set_yticks(y_pos)
ax1.set_yticklabels(labels, fontsize=9)
ax1.set_xlabel("Estimated Treatment Effect on HbA1c\n(percentage points)", fontsize=10)
ax1.set_title("A", fontsize=14, fontweight="bold", loc="left")
ax1.invert_yaxis()
# Place CI annotations to the right of the error bars
for i, (ate, lo, hi) in enumerate(zip(ates, ci_los, ci_his)):
    ax1.text(max(hi, 0) + 0.08, i, f"{ate:.2f} [{lo:.2f}, {hi:.2f}]",
             va="center", ha="left", fontsize=8.5, color="black")
ax1.set_xlim(-1.5, 1.0)

# --- Panel B: A1c trajectories for Q1 subgroup (baseline A1c >= 9%) ---
q1 = trimmed[trimmed["baseline_a1c"] >= 9.0].copy()
t_q1 = q1[q1["treated"] == 1]
c_q1 = q1[q1["treated"] == 0]

time_points = [0, 1]
t_means = [t_q1["baseline_a1c"].mean(), t_q1["followup_a1c"].mean()]
c_means = [c_q1["baseline_a1c"].mean(), c_q1["followup_a1c"].mean()]
t_sems = [t_q1["baseline_a1c"].sem(), t_q1["followup_a1c"].sem()]
c_sems = [c_q1["baseline_a1c"].sem(), c_q1["followup_a1c"].sem()]

ax2.errorbar(time_points, t_means, yerr=t_sems, fmt="-o", color="#d62728",
             linewidth=2.5, markersize=10, capsize=5, label=f"Treated (N={len(t_q1)})")
ax2.errorbar(time_points, c_means, yerr=c_sems, fmt="-s", color="#2171b5",
             linewidth=2.5, markersize=10, capsize=5, label=f"Control (N={len(c_q1)})")
ax2.set_xticks([0, 1])
ax2.set_xticklabels(["Baseline", "Follow-up"], fontsize=10)
ax2.set_ylabel("Mean HbA1c (%)", fontsize=10)
ax2.set_title("B", fontsize=14, fontweight="bold", loc="left")
ax2.legend(loc="upper center", bbox_to_anchor=(0.5, -0.12), ncol=2, fontsize=9, frameon=False)

diff = t_q1["a1c_change"].mean() - c_q1["a1c_change"].mean()

fig.text(0.28, 0.02, "Panel A: Primary and sensitivity estimates",
         ha="center", fontsize=9, style="italic")
fig.text(0.76, 0.02, "Panel B: Subgroup with baseline HbA1c >= 9%",
         ha="center", fontsize=9, style="italic")

plt.tight_layout(rect=[0, 0.05, 1, 1])
for ext in ["png", "pdf"]:
    fig.savefig(FIG_DIR / f"figure1_treatment_effects.{ext}", dpi=300, bbox_inches="tight")
print(f"Figure 1 saved: {FIG_DIR / 'figure1_treatment_effects.png'}")
plt.close()

# ============================================================
# eFIGURE 2: Cost-effectiveness plane
# ============================================================
np.random.seed(42)
N_SIM = 10000

fig, ax = plt.subplots(1, 1, figsize=(8, 6))

for key, color, marker, label in [
    ("primary", "#2171b5", "o", "Mean HbA1c (primary, ATE = −0.56 pp)"),
    ("sensitivity", "#6baed6", "s", "Last HbA1c (sensitivity, ATE = −0.29 pp)")
]:
    eff = {"primary": {"ate": -0.558, "ci_lo": -1.006, "ci_hi": -0.111},
           "sensitivity": {"ate": -0.289, "ci_lo": -0.570, "ci_hi": -0.007}}[key]
    se = (eff["ci_hi"] - eff["ci_lo"]) / (2 * 1.96)

    qaly_draws = []
    cost_draws = []
    recode = [("mi", 0.21350, 0.082, 45000, 0.055),
              ("stroke", 0.33650, 0.055, 55000, 0.164),
              ("renal", 0.13690, 0.045, 85000, 0.078),
              ("vision", 0.14490, 0.075, 15000, 0.050),
              ("chf", 0.20920, 0.065, 32000, 0.075),
              ("death", 0.16590, 0.065, 0, 1.0)]
    for _ in range(N_SIM):
        a1c = np.random.normal(eff["ate"], se)
        total_qaly = 0
        total_savings = 0
        for comp, beta, base_rate, cost_per, qaly_dec in recode:
            hr_change = np.exp(beta * a1c)
            arr = base_rate * (1 - hr_change)
            total_savings += arr * cost_per
            total_qaly += arr * qaly_dec * 10

        cost_per_month = np.random.triangular(31.81, 67.74, 147.33)
        days = np.random.triangular(84, 118, 163)
        months = days / 30.5
        int_cost = cost_per_month * months
        acute_sav = np.random.triangular(49.69, 252.70, 519.67) * months
        net = int_cost - acute_sav - total_savings
        cost_draws.append(net)
        qaly_draws.append(total_qaly)

    ax.scatter(qaly_draws[::10], [c for c in cost_draws[::10]], alpha=0.15,
               s=8, color=color, marker=marker)
    ax.scatter(np.mean(qaly_draws), np.mean(cost_draws), s=120, color=color,
               marker=marker, edgecolors="black", linewidths=1, label=label, zorder=5)

ax.axhline(0, color="gray", linewidth=0.5, linestyle="--")
ax.axvline(0, color="gray", linewidth=0.5, linestyle="--")
qaly_range = np.linspace(0, max(0.15, ax.get_xlim()[1]), 100)
ax.plot(qaly_range, qaly_range * 50000, color="green", linewidth=1, linestyle=":",
        alpha=0.5, label="WTP = $50,000/QALY")
ax.set_xlabel("Incremental QALYs", fontsize=11)
ax.set_ylabel("Incremental Net Cost ($)", fontsize=11)
ax.set_title("Cost-Effectiveness Plane", fontsize=12, fontweight="bold")
ax.legend(fontsize=9, loc="upper left")

plt.tight_layout()
for ext in ["png", "pdf"]:
    fig.savefig(FIG_DIR / f"efigure2_cost_effectiveness.{ext}", dpi=300, bbox_inches="tight")
print(f"eFigure 2 saved: {FIG_DIR / 'efigure2_cost_effectiveness.png'}")
plt.close()

print("\nQ1 subgroup (A1c >= 9%):")
print(f"  N_treated={len(t_q1)}, N_control={len(c_q1)}")
print(f"  Treated: {t_means[0]:.1f}% -> {t_means[1]:.1f}% (change={t_q1['a1c_change'].mean():.2f})")
print(f"  Control: {c_means[0]:.1f}% -> {c_means[1]:.1f}% (change={c_q1['a1c_change'].mean():.2f})")
print(f"  Unadjusted diff-in-change: {diff:.2f}")
